Update ospfd.init

diff --git a/quagga-isep/ospfd.init b/quagga-isep/ospfd.init
--- a/quagga-isep/ospfd.init
+++ b/quagga-isep/ospfd.init
@@ -37,7 +37,7 @@ case "$1" in
 		echo $"Insufficient privilege" 1>&2
 		exit 4
 	fi
-
+	[ -x $cmd ] || { echo "$cmd not found"; exit 5; }
 	log_daemon_msg "Starting $PROG" "$PROG"
 	#start_daemon $cmd -d $OSPFD_OPTS -f $CONF_FILE
 	$cmd -f $CONF_FILE -i $PID_FILE &
